services:
  - type: web
    name: cineplay
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_TMDB_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    staticPublishPath: dist
